version: '3'
services: 
    db:
        image: 'postgres:latest'
        environment: 
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: test_mb_labs
        volumes: 
            - ./pgdata:/var/lib/postgresql/data
        ports: 
            - "5432:5432"        

    app:
        container_name: mb_labs-api
        restart: always
        build: .
        ports:
            - "3333:3333"   
        depends_on: 
            - db         